### ISSUE TITLE
Impossible d'ajouter un nouveau calendrier

### ISSUE THREAD

**Issue by leo29plns** [timecalendar/timecalendar#25]
Bonjour, 

Il m'est impossible de générer un calendrier à partir d'un lien ical, (via app ios ou web). J'ai tenté de le faire avec un ancien lien qui avait fonctionné l'an passé, même erreur.

Depuis le web, j'ai une erreur 500 lors de la requête vers https://api.timecalendar.app/calendar/custom

{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}

**Comment by samuelprak** [comment]
Bonjour !

Une mise à jour de l'application est prévue dans les prochains jours pour corriger le problème. Je te tiendrai au courant lorsque la mise à jour sera disponible sur Android et iOS.

**Comment by leo29plns** [comment]
Tout semble fonctionner, merci beaucoup :)
